### ISSUE TITLE
add polygon drawing tool

### ISSUE THREAD

**Issue by justinmeiners** [justinmeiners/classic-colors#1]

**Comment by MagnetarRocket** [comment]
Actualy, i may have created a "shapes" icon for that, however, it's too fuzzy as of late

**Comment by MagnetarRocket** [comment]
I now have an icon for this. But don't know what style to draw in though.

**Comment by MagnetarRocket** [comment]
Here are the two icons:
![polyDraw](https://user-images.githubusercontent.com/53055079/156691129-ac73a4c7-555f-4d43-811b-430afdaba53c.png)
![polyDraw_m](https://user-images.githubusercontent.com/53055079/156691146-c72a7b0d-7f28-428a-96b6-65264361c2f8.png)

**Comment by justinmeiners** [comment]
@MagnetarRocket I finally got a version of this feature in. It came with a lot of other improvements, so I hope nothing is too broken.

 I did make a different icon for the polygon, but it was based on your selection icon, so I appreciate that. I may still change the icons.
