### ISSUE TITLE
Provide better instructions for increasing shared memory size on Mac, in order to support MIT-SHM

### ISSUE THREAD

**Issue by dpeterc** [justinmeiners/classic-colors#13]
Normal Mac user might not be familiar with proper ways of increasing shared memory size, in order to support MIT-SHM extension, which makes program work with decent speed.

In the installation instructions for MacOS, instruct the user to create file /etc/sysctl.conf
with the following contents:
kern.sysv.shmmax=134217728
kern.sysv.shmmin=1
kern.sysv.shmmni=1024
kern.sysv.shmseg=256
kern.sysv.shmall=32768
and reboot the system after creating the file.
You could also provide a script to be executed with sudo permissions, which would create such a file, or append this contents to existing /etc/sysctl.conf file.
Anyway, at the program's current level (no .dmg installation file), adventurous Mac users will be able to do this change.

**Comment by justinmeiners** [comment]
Finally got this in! Thanks.
