### ISSUE TITLE
Sugestion: use extended Motif file selection box instead of the standard one

### ISSUE THREAD

**Issue by dpeterc** [justinmeiners/classic-colors#16]
This is a low effort solution to make the program look more modern and accessible to novice users, which have previous UI experience from modern GUI systems.
https://sourceforge.net/projects/motifextfsb/

**Comment by MagnetarRocket** [comment]
I think this should be "able to use different file selection boxes depending upon environments", as the two possible major motif environments maintained today have noticeably different file selection dialogs:

Open source CDE: https://docs.oracle.com/cd/E19455-01/806-2915/6jc3nfto2/index.html
MaxxDesktop: https://techpubs.jurassic.nl/manuals/0650/developer/IIDsktp_IG/sgi_html/ch04.html

**Comment by justinmeiners** [comment]
@MagnetarRocket Do you have any suggestions about how to support those easily? I would prefer one solution unless there is a really good reason.

**Comment by dpeterc** [comment]
The switch between normal Motif FSB and SGI enhanced FSB can only be done in compile/link phase, changes to the source are minimal (if you do not explicitly use any of the extra features), as the documentation says:
set SgNuseEnhancedFSB to TRUE and link wiht -lSgm
Problem is, that it is hard to get SGI enhanced Motif libraries, if not on old SGI hardware (probably not your intended user base), or from Maxx desktop, which appears to be stopped at this moment, and source distribution was never released.

On the other hand, Extended Motif FSB is free with source, you can use it anywhere.
https://sourceforge.net/projects/motifextfsb/
It is a spinoff from xnedit
https://sourceforge.net/projects/xnedit/
with all the xnedit dependencies removed, and some extra functions, which makes it more general purpose.
You do not need any extra libraries, Extended Motif FSB is just an extra widget which add to your source distribution.
It also comes with a standalone sample C program, which shows how to set the new FSB up properly.

If you wanted, you could make the use of normal Motif FSB and the Extended Motif FSB configurable option in the program, since stock Motif will still contain the old widget. But some extra code will be required; maybe this effort can be spared for more important stuff. I don't think the old Motif FSB has a fan club :-)

**Comment by MagnetarRocket** [comment]
In the case of what i put in, supported by the default variant of motif of that environment. however the suggested save file dialog relies upon a project called [microline](https://sourceforge.net/projects/microline/) , and it relies upon imake; anything i encountered with imake so far is difficult for me to configure a simple make adjustment for and i never had much good luck with imake + homebrew on mac OS. possibly PKGSRC mac?

for an "only one soution", i would go for a save dialog styled after the IRIX one. without "Filter".

**Comment by dpeterc** [comment]
Like i mentioned above, the IRIX version of FBS is not open source, so it is hard to use, if you have to compile it for new platform like Apple M1.
The Extended Motif FSB does not depend on Imake. Microline widget library can be compiled as part of xnedit (or nedit, but FSB requires some changes to Microline for full capabilities). This dependency did not create problems for nedit over the many years of distribution. Base Motif does not provide a strong multicolumn list widget, while Microline has it, and this is necessary for the detail view of FSB (filename, date, file size).

**Comment by justinmeiners** [comment]
Thank you both for input. When I looked before Extended Motif FSB looked good, after stripping up some of those optional dependencies. I will likely do that.

Unfortunately, I can see a slight tension in interests. To make it clear, I aim to use motif to support modern platforms and desktop environments. I am less interested in making trade-offs which accommodate existing motif ecosystems.

@MagnetarRocket Please continue to propose any changes that would make your life better, with this in mind.
