### ISSUE TITLE
Problems compiling with pkgsrc

### ISSUE THREAD

**Issue by MagnetarRocket** [justinmeiners/classic-colors#22]
On my 2nd M1 mac, I have pkgsrc as the sole package-manager, however, attempting to compile Classic-colors there reveals a new set of problems:

- pkg-config is not installed by default.

- xorgproto must be installed

- again, -I and -L flags have not been set properly, pkgsrc is a different beast then compared to homebrew.

if anybody's curious of why I have netBSD's package manager on my Mac:
http://pkgsrc.joyent.com/install-on-osx/

ps: I've attempted to install netBSD on a virtual machine to see if I could also compile classic-colors on it (to see if it was different in steps compared to the pkgsrc of macOS), however I can't find a suitable virtual machine, and also all attempts at installing fail. Might try my raspberry Pi when I have the time.

**Comment by justinmeiners** [comment]
@MagnetarRocket 

See #24. I just made fixes for NetBSD. Some of them will also automatically carry over to mac, some will not. Can you give it a try and let me know where it breaks?

**Comment by MagnetarRocket** [comment]
It works. Nothing broken so far.

**Comment by justinmeiners** [comment]
Great, am I good to close this then?

**Comment by MagnetarRocket** [comment]
Close.
