### ISSUE TITLE
Wont build on NetBSD

### ISSUE THREAD

**Issue by pfr-dev** [justinmeiners/classic-colors#24]
I'm guessing the `makefile` needs some tweaks but I just assumed that if it builds on OBSD then it should build on Net.

after running `./configure` I get:
```
~/Downloads/classic-colors $ make
make: don't know how to make icons/%.png. Stop

make: stopped in /home/dave/Downloads/classic-colors
```
it gets immediately stopped in it's tracks. I'm not so savvy to figure this out, any ideas? 
Cheers

**Comment by justinmeiners** [comment]
Looks like I am using gnumake features here, which are not available in the netbsd base make. You can install gnumake through your packages.

Give that a try and let me if that works out. Either way I'll install netbsd and see what we need.

Thanks.

**Comment by justinmeiners** [comment]
![netbsd](https://user-images.githubusercontent.com/3220045/160259773-e26fb313-3328-45ee-9874-8de0e02ce099.png)

I did get it to work, but it was a bit of a pain. I don't know enough about netbsd or pkgsrc to know the ideal way to query the information I need in the configure step.

**Comment by justinmeiners** [comment]
I just touched up the configure script, and I think it's all working now. Want to give it a try?
