### ISSUE TITLE
inability to compile on macbook m1

### ISSUE THREAD

**Issue by MagnetarRocket** [justinmeiners/classic-colors#8]
I'm unable to compile classic-colors on a m1 macbook air, attempting to see if this is also a problem with any other motif apps (mwm-utils, emwm, xnedit) all showed a similar problem (this is the classic-colors program):

> In file included from ui_color.c:18:
> ./ui.h:26:10: fatal error: 'Xm/Xm.h' file not found
> #include <Xm/Xm.h>
>          ^~~~~~~~~
> 1 error generated.
> make: *** [ui_color.o] Error 1

all showed that Xm.h was absent, now my preferences is working on a external HHD as I don't have much space on my mac, and i don't want to write to when possible on SSD's. also the file system on the external HHD is case-sensitive because i wanted to have a "fully unix disk".

now someone had found a way around this:
https://stackoverflow.com/questions/46872922/broken-c-std-libraries-on-macos-high-sierra-10-13/47401866#47401866

But the main problem i have i think is a way to automate the above so i don't have to do this repeatedly, a shell script would be nice but i'm new to zsh shell scripting (don't ask me how loooooooong i've been doing most of my programing stuff on windows).

also i don't have a /usr/local/include directory.

**Comment by justinmeiners** [comment]
My guess is it's just your non-standard installation, and not anything about the M1.

> also i don't have a /usr/local/include directory.

Since it's just motif (`Xm.h`), the stackoverflow links is probably not what you want.
I probably have the wrong include path (assuming `/usr/local/include`).
You can run:

    brew --prefix openmotif

to find it. The fix would hopefully be replacing or adding that path in `config.mk` (after running `./configure` for the first time). 

I would like to make detecting that path better in the future.
If there are still problems, I can get a hold of an M1 and try it out.

**Comment by MagnetarRocket** [comment]
fiddling around with the other motif apps(i think i have them all in my github stars section) in the makefile all show a similar problem of the motif libraries. the apps are in the links below:

new motif apps (came after the release of mac osx):
https://github.com/justinmeiners/classic-colors (this app we're talking about now)
https://github.com/alx210/mwm-utils (sir alx210 is a gold mine of motif apps)
https://github.com/alx210/emwm
https://github.com/alx210/ximaging
https://github.com/unixwork/xnedit

old motif apps (came before the release of mac osx, these are so old i don't think they would compile on a modern unix system even if i wanted them):
https://github.com/ThomasAdam/moxfm
https://github.com/edorig/xrolodex

**Comment by danlshields** [comment]
As a workaround, `CFLAGS="-I/opt/homebrew/include -L/opt/homebrew/lib" make` works

**Comment by MagnetarRocket** [comment]
The colors and scroll bar are atypical, but those are settable in the .Xdefaults file
<img width="1680" alt="Screen Shot 2021-10-20 at 10 12 30 PM" src="https://user-images.githubusercontent.com/53055079/138205274-f8457025-b9f4-4b82-b867-fe6e72709189.png">

**Comment by MagnetarRocket** [comment]
Oh, the `CFLAGS=-I/opt/homebrew/include -L/opt/homebrew/lib` thing, doing this to alx210's apps make them work expect for Mwm-utils, may make a simplfied varient of it removing the lock-screen apps
